version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dbos
      - MYSQL_ROOT_PASSWORD=12421**
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./mysql_dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  web:
    depends_on:
      db:
        condition: "service_healthy"
    environment:
    - MYSQL_USER=root
    - MYSQL_DATABASE=dbos
    - MYSQL_ROOT_PASSWORD=12421**
    - EMAIL_HOST_USER=kalihun@netos.com
    - EMAIL_HOST_PASSWORD=sophianice@123
    - MYSQL_PORT=3306
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
